// Portugal — staples & starches (bread, cereals, rice, pasta, potato, flours,
// morning cereals). SYNTHETIC development data; per-100 g approximations with
// honest confidence/provenance. id prefix: `pt-st-`.

import type { FoodInput } from "../catalogTypes.js";

export const PT_STAPLES: FoodInput[] = [
  // ---------------------------------------------------------------------------
  // Breads & bakery staples
  // ---------------------------------------------------------------------------
  {
    id: "pt-st-pao-alentejano",
    type: "ingredient",
    names: {
      pt: { name: "Pão alentejano", synonyms: ["pão do Alentejo"] },
      en: { name: "Alentejo-style wheat bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 51.0,
    energyKcal: 253,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-de-mistura",
    type: "ingredient",
    names: {
      pt: { name: "Pão de mistura", synonyms: ["pão de trigo e centeio"] },
      en: { name: "Wheat-and-rye mixed bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 243,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-integral",
    type: "ingredient",
    names: {
      pt: { name: "Pão integral", synonyms: ["pão de trigo integral"] },
      en: { name: "Wholemeal bread", synonyms: ["whole wheat bread"] },
    },
    countries: ["PT"],
    carbGrams: 41.0,
    energyKcal: 232,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-papo-seco",
    type: "ingredient",
    names: {
      pt: { name: "Papo-seco", synonyms: ["carcaça", "pão de trigo"] },
      en: { name: "Portuguese white bread roll", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 55.0,
    energyKcal: 274,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-pao-de-agua",
    type: "ingredient",
    names: {
      pt: { name: "Pão de água", synonyms: [] },
      en: { name: "Water bread roll", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 53.0,
    energyKcal: 262,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-regueifa",
    type: "ingredient",
    names: {
      pt: { name: "Regueifa", synonyms: [] },
      en: { name: "Regueifa sweet white loaf", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 54.0,
    energyKcal: 284,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-bolo-do-caco",
    type: "ingredient",
    names: {
      pt: { name: "Bolo do caco", synonyms: ["pão de batata-doce da Madeira"] },
      en: { name: "Madeiran sweet-potato flatbread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 257,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-de-centeio",
    type: "ingredient",
    names: {
      pt: { name: "Pão de centeio", synonyms: [] },
      en: { name: "Rye bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 231,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-saloio",
    type: "ingredient",
    names: {
      pt: { name: "Pão saloio", synonyms: [] },
      en: { name: "Rustic country wheat bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 251,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-de-forma-integral",
    type: "packaged",
    names: {
      pt: { name: "Pão de forma integral", synonyms: ["pão de forma de trigo integral"] },
      en: { name: "Wholemeal sliced sandwich bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 40.0,
    energyKcal: 236,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-tosta-pao",
    type: "ingredient",
    names: {
      pt: { name: "Pão tostado", synonyms: ["torrada", "tosta"] },
      en: { name: "Toasted white bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 65.0,
    energyKcal: 293,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-baguete",
    type: "ingredient",
    names: {
      pt: { name: "Baguete", synonyms: ["cacete"] },
      en: { name: "Baguette", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 56.0,
    energyKcal: 271,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-broa-de-avintes",
    type: "ingredient",
    names: {
      pt: { name: "Broa de Avintes", synonyms: [] },
      en: { name: "Avintes dark rye-and-corn bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 228,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-de-leite",
    type: "ingredient",
    names: {
      pt: { name: "Pão de leite", synonyms: [] },
      en: { name: "Milk bread roll", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 53.0,
    energyKcal: 305,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-pao-caseiro",
    type: "ingredient",
    names: {
      pt: { name: "Pão caseiro", synonyms: ["pão de trigo caseiro"] },
      en: { name: "Homemade rustic wheat bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 250,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-pao-ralado",
    type: "ingredient",
    names: {
      pt: { name: "Pão ralado", synonyms: ["pão seco ralado"] },
      en: { name: "Breadcrumbs", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 72.0,
    energyKcal: 372,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },

  // ---------------------------------------------------------------------------
  // Rice variants
  // ---------------------------------------------------------------------------
  {
    id: "pt-st-arroz-integral-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Arroz integral cozido", synonyms: ["arroz integral"] },
      en: { name: "Cooked brown rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 23.0,
    energyKcal: 111,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-arroz-agulha-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Arroz agulha cozido", synonyms: ["arroz de grão longo cozido"] },
      en: { name: "Cooked long-grain rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 28.0,
    energyKcal: 130,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-arroz-carolino-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Arroz carolino cozido", synonyms: ["arroz de grão curto cozido"] },
      en: { name: "Cooked carolino short-grain rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 28.0,
    energyKcal: 129,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-arroz-basmati-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Arroz basmati cozido", synonyms: [] },
      en: { name: "Cooked basmati rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 25.0,
    energyKcal: 121,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-arroz-vaporizado-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Arroz vaporizado cozido", synonyms: ["arroz parboilizado cozido"] },
      en: { name: "Cooked parboiled rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 26.0,
    energyKcal: 123,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-arroz-cru",
    type: "ingredient",
    names: {
      pt: { name: "Arroz branco cru", synonyms: ["arroz cru"] },
      en: { name: "Raw white rice", synonyms: ["uncooked white rice"] },
    },
    countries: ["PT"],
    carbGrams: 78.0,
    energyKcal: 356,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },

  // ---------------------------------------------------------------------------
  // Pasta
  // ---------------------------------------------------------------------------
  {
    id: "pt-st-macarrao-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Macarrão cozido", synonyms: ["massa cozida"] },
      en: { name: "Cooked macaroni pasta", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 26.0,
    energyKcal: 131,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-massa-integral-cozida",
    type: "ingredient",
    names: {
      pt: { name: "Massa integral cozida", synonyms: ["massa de trigo integral cozida"] },
      en: { name: "Cooked wholewheat pasta", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 27.0,
    energyKcal: 133,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-esparguete-cru",
    type: "ingredient",
    names: {
      pt: { name: "Esparguete cru", synonyms: ["esparguete seco"] },
      en: { name: "Dry spaghetti", synonyms: ["uncooked spaghetti"] },
    },
    countries: ["PT"],
    carbGrams: 72.0,
    energyKcal: 358,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
  {
    id: "pt-st-massa-cotovelo-cozida",
    type: "ingredient",
    names: {
      pt: { name: "Massa cotovelo cozida", synonyms: ["cotovelinhos cozidos"] },
      en: { name: "Cooked elbow macaroni", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 26.0,
    energyKcal: 130,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-lasanha-folha-cozida",
    type: "ingredient",
    names: {
      pt: { name: "Folha de lasanha cozida", synonyms: ["placa de lasanha cozida"] },
      en: { name: "Cooked lasagne sheet", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 27.0,
    energyKcal: 135,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-noodles-cozidos",
    type: "ingredient",
    names: {
      pt: { name: "Noodles cozidos", synonyms: ["massa de noodles cozida"] },
      en: { name: "Cooked egg noodles", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 25.0,
    energyKcal: 138,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-massa-pevide-cozida",
    type: "ingredient",
    names: {
      pt: { name: "Massa pevide cozida", synonyms: ["massinha para sopa cozida", "letras cozidas"] },
      en: { name: "Cooked small soup pasta", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 26.0,
    energyKcal: 130,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-massa-seca-crua",
    type: "ingredient",
    names: {
      pt: { name: "Massa seca crua", synonyms: ["massa crua"] },
      en: { name: "Dry pasta", synonyms: ["uncooked pasta"] },
    },
    countries: ["PT"],
    carbGrams: 72.0,
    energyKcal: 356,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },

  // ---------------------------------------------------------------------------
  // Potato & tubers
  // ---------------------------------------------------------------------------
  {
    id: "pt-st-batata-frita-caseira",
    type: "ingredient",
    names: {
      pt: { name: "Batata frita caseira", synonyms: ["batata frita palito caseira"] },
      en: { name: "Home-fried potato chips", synonyms: ["home-fried french fries"] },
    },
    countries: ["PT"],
    carbGrams: 34.0,
    energyKcal: 312,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-batata-assada",
    type: "ingredient",
    names: {
      pt: { name: "Batata assada", synonyms: ["batata no forno"] },
      en: { name: "Roast potato", synonyms: ["baked potato"] },
    },
    countries: ["PT"],
    carbGrams: 24.0,
    energyKcal: 149,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-batata-a-murro",
    type: "ingredient",
    names: {
      pt: { name: "Batata a murro", synonyms: ["batata assada com pele"] },
      en: { name: "Smashed skin-on baked potato", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 22.0,
    energyKcal: 120,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-pure-de-batata",
    type: "ingredient",
    names: {
      pt: { name: "Puré de batata", synonyms: ["esmagada de batata"] },
      en: { name: "Mashed potato", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 15.0,
    energyKcal: 88,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-batata-doce-cozida",
    type: "ingredient",
    names: {
      pt: { name: "Batata doce cozida", synonyms: [] },
      en: { name: "Boiled sweet potato", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 90,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-batata-doce-assada",
    type: "ingredient",
    names: {
      pt: { name: "Batata doce assada", synonyms: ["batata doce no forno"] },
      en: { name: "Roast sweet potato", synonyms: ["baked sweet potato"] },
    },
    countries: ["PT"],
    carbGrams: 24.0,
    energyKcal: 112,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-inhame-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Inhame cozido", synonyms: ["inhame dos Açores cozido"] },
      en: { name: "Boiled yam", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 26.0,
    energyKcal: 118,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-batata-frita-forno-congelada",
    type: "packaged",
    names: {
      pt: { name: "Batata frita de forno (congelada)", synonyms: ["batata palito de forno"] },
      en: { name: "Oven-baked frozen potato chips", synonyms: ["oven fries"] },
    },
    countries: ["PT"],
    carbGrams: 33.0,
    energyKcal: 188,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },

  // ---------------------------------------------------------------------------
  // Other grains & morning cereals
  // ---------------------------------------------------------------------------
  {
    id: "pt-st-flocos-de-aveia",
    type: "ingredient",
    names: {
      pt: { name: "Flocos de aveia", synonyms: ["aveia em flocos"] },
      en: { name: "Rolled oats", synonyms: ["oat flakes"] },
    },
    countries: ["PT"],
    carbGrams: 60.0,
    energyKcal: 375,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-papas-de-aveia",
    type: "ingredient",
    names: {
      pt: { name: "Papas de aveia", synonyms: ["aveia cozida em água"] },
      en: { name: "Oat porridge (cooked in water)", synonyms: ["oatmeal"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 71,
    confidence: "high",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast"],
  },
  {
    id: "pt-st-muesli",
    type: "packaged",
    names: {
      pt: { name: "Muesli", synonyms: ["mistura de cereais e frutos secos"] },
      en: { name: "Muesli", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 60.0,
    energyKcal: 362,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-st-corn-flakes",
    type: "packaged",
    names: {
      pt: { name: "Flocos de milho (corn flakes)", synonyms: ["cereais de pequeno-almoço de milho"] },
      en: { name: "Corn flakes", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 84.0,
    energyKcal: 378,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast"],
  },
  {
    id: "pt-st-cereais-farelo",
    type: "packaged",
    names: {
      pt: { name: "Cereais de farelo de trigo", synonyms: ["flocos de farelo", "bran flakes"] },
      en: { name: "Wheat bran flakes", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 67.0,
    energyKcal: 320,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast"],
  },
  {
    id: "pt-st-cuscuz-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Cuscuz cozido", synonyms: ["couscous cozido"] },
      en: { name: "Cooked couscous", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 23.0,
    energyKcal: 112,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-quinoa-cozida",
    type: "ingredient",
    names: {
      pt: { name: "Quinoa cozida", synonyms: ["quinoa cozinhada"] },
      en: { name: "Cooked quinoa", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 21.0,
    energyKcal: 120,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-milho-doce-em-grao",
    type: "ingredient",
    names: {
      pt: { name: "Milho doce em grão", synonyms: ["milho doce de conserva"] },
      en: { name: "Sweetcorn kernels", synonyms: ["canned sweetcorn"] },
    },
    countries: ["PT"],
    carbGrams: 19.0,
    energyKcal: 96,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-st-semola-de-trigo",
    type: "ingredient",
    names: {
      pt: { name: "Sêmola de trigo", synonyms: ["semolina"] },
      en: { name: "Wheat semolina", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 72.0,
    energyKcal: 360,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
  {
    id: "pt-st-bulgur-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Bulgur cozido", synonyms: ["trigo bulgur cozido"] },
      en: { name: "Cooked bulgur wheat", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 19.0,
    energyKcal: 83,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-st-trigo-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Trigo em grão cozido", synonyms: ["trigo cozido"] },
      en: { name: "Cooked wheat berries", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 21.0,
    energyKcal: 110,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },

  // ---------------------------------------------------------------------------
  // Flours
  // ---------------------------------------------------------------------------
  {
    id: "pt-st-farinha-de-trigo",
    type: "ingredient",
    names: {
      pt: { name: "Farinha de trigo", synonyms: ["farinha de trigo tipo 55"] },
      en: { name: "Wheat flour", synonyms: ["white wheat flour"] },
    },
    countries: ["PT"],
    carbGrams: 72.0,
    energyKcal: 350,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
  {
    id: "pt-st-farinha-integral",
    type: "ingredient",
    names: {
      pt: { name: "Farinha integral de trigo", synonyms: ["farinha de trigo integral"] },
      en: { name: "Wholemeal wheat flour", synonyms: ["whole wheat flour"] },
    },
    countries: ["PT"],
    carbGrams: 64.0,
    energyKcal: 340,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
  {
    id: "pt-st-maizena",
    type: "ingredient",
    names: {
      pt: { name: "Amido de milho", synonyms: ["maizena", "farinha fina de milho"] },
      en: { name: "Cornstarch", synonyms: ["corn flour"] },
    },
    countries: ["PT"],
    carbGrams: 88.0,
    energyKcal: 343,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
  {
    id: "pt-st-farinha-de-milho",
    type: "ingredient",
    names: {
      pt: { name: "Farinha de milho", synonyms: ["farinha de milho amarela"] },
      en: { name: "Cornmeal", synonyms: ["maize flour"] },
    },
    countries: ["PT"],
    carbGrams: 73.0,
    energyKcal: 361,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
  {
    id: "pt-st-farinha-de-centeio",
    type: "ingredient",
    names: {
      pt: { name: "Farinha de centeio", synonyms: [] },
      en: { name: "Rye flour", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 70.0,
    energyKcal: 335,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
  },
];
