// Portugal — protein & dairy (meat, poultry, fish, seafood, eggs, cured meats /
// enchidos, cheese, dairy). SYNTHETIC development data; per-100 g approximations
// with honest confidence/provenance. id prefix: `pt-po-`.

import type { FoodInput } from "../catalogTypes.js";

export const PT_PROTEIN: FoodInput[] = [
  // --- Meat & poultry (available carb ≈ 0) -------------------------------
  {
    id: "pt-po-peito-de-frango-grelhado",
    type: "ingredient",
    names: {
      pt: { name: "Peito de frango grelhado", synonyms: ["frango grelhado"] },
      en: { name: "Grilled chicken breast", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 165,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-coxa-de-frango-assada",
    type: "ingredient",
    names: {
      pt: { name: "Coxa de frango assada", synonyms: ["perna de frango"] },
      en: { name: "Roast chicken thigh", synonyms: ["chicken leg"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 215,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-peito-de-peru",
    type: "ingredient",
    names: {
      pt: { name: "Peito de peru", synonyms: ["bife de peru"] },
      en: { name: "Turkey breast", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 135,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-bife-de-vaca-grelhado",
    type: "ingredient",
    names: {
      pt: { name: "Bife de vaca grelhado", synonyms: ["bife de novilho"] },
      en: { name: "Grilled beef steak", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 210,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-lombo-de-vaca",
    type: "ingredient",
    names: {
      pt: { name: "Lombo de vaca", synonyms: ["bife do lombo", "lombo de novilho"] },
      en: { name: "Beef tenderloin", synonyms: ["sirloin"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 180,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-carne-de-vaca-picada",
    type: "ingredient",
    names: {
      pt: { name: "Carne de vaca picada", synonyms: ["carne picada"] },
      en: { name: "Minced beef", synonyms: ["ground beef"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 250,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-lombo-de-porco",
    type: "ingredient",
    names: {
      pt: { name: "Lombo de porco", synonyms: ["lombo assado"] },
      en: { name: "Pork loin", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 145,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-entremeada-de-porco",
    type: "ingredient",
    names: {
      pt: { name: "Entremeada de porco", synonyms: ["barriga de porco"] },
      en: { name: "Pork belly", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 520,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-febras-de-porco",
    type: "ingredient",
    names: {
      pt: { name: "Febras de porco", synonyms: ["febras grelhadas"] },
      en: { name: "Pork loin steaks", synonyms: ["pork escalopes"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 150,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-costeleta-de-porco",
    type: "ingredient",
    names: {
      pt: { name: "Costeleta de porco", synonyms: ["costeleta grelhada"] },
      en: { name: "Pork chop", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 230,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-coelho",
    type: "ingredient",
    names: {
      pt: { name: "Coelho", synonyms: ["carne de coelho"] },
      en: { name: "Rabbit", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 170,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-borrego",
    type: "ingredient",
    names: {
      pt: { name: "Borrego", synonyms: ["carne de borrego", "cabrito"] },
      en: { name: "Lamb", synonyms: ["kid goat"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 260,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-peito-de-pato",
    type: "ingredient",
    names: {
      pt: { name: "Peito de pato", synonyms: ["magret de pato"] },
      en: { name: "Duck breast", synonyms: ["magret"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 200,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-figado-de-vaca",
    type: "ingredient",
    names: {
      pt: { name: "Fígado de vaca", synonyms: ["iscas de fígado"] },
      en: { name: "Beef liver", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.5,
    energyKcal: 135,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },

  // --- Cured meats / enchidos --------------------------------------------
  {
    id: "pt-po-chourico",
    type: "ingredient",
    names: {
      pt: { name: "Chouriço", synonyms: ["chouriço de carne"] },
      en: { name: "Chouriço (Portuguese cured sausage)", synonyms: ["chorizo"] },
    },
    countries: ["PT"],
    carbGrams: 1.5,
    energyKcal: 330,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  {
    id: "pt-po-linguica",
    type: "ingredient",
    names: {
      pt: { name: "Linguiça", synonyms: ["linguiça fumada"] },
      en: { name: "Linguiça (thin cured sausage)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 300,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  {
    id: "pt-po-farinheira",
    type: "ingredient",
    names: {
      pt: { name: "Farinheira", synonyms: ["farinheira de Portalegre"] },
      en: { name: "Farinheira (flour & pork-fat sausage)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 24,
    energyKcal: 400,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-morcela",
    type: "ingredient",
    names: {
      pt: { name: "Morcela", synonyms: ["chouriço de sangue"] },
      en: { name: "Morcela (blood sausage)", synonyms: ["blood pudding"] },
    },
    countries: ["PT"],
    carbGrams: 2.5,
    energyKcal: 340,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-presunto",
    type: "ingredient",
    names: {
      pt: { name: "Presunto", synonyms: ["presunto curado"] },
      en: { name: "Presunto (dry-cured ham)", synonyms: ["cured ham"] },
    },
    countries: ["PT"],
    carbGrams: 0.5,
    energyKcal: 250,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["breakfast", "snack", "lunch"],
  },
  {
    id: "pt-po-fiambre",
    type: "packaged",
    names: {
      pt: { name: "Fiambre", synonyms: ["fiambre da perna"] },
      en: { name: "Fiambre (cooked ham)", synonyms: ["cooked ham"] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 110,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    mealContextTags: ["breakfast", "snack", "lunch"],
  },
  {
    id: "pt-po-salpicao",
    type: "ingredient",
    names: {
      pt: { name: "Salpicão", synonyms: ["salpicão de lombo"] },
      en: { name: "Salpicão (cured pork-loin sausage)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 340,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch"],
  },
  {
    id: "pt-po-alheira",
    type: "ingredient",
    names: {
      pt: { name: "Alheira", synonyms: ["alheira de Mirandela"] },
      en: { name: "Alheira (bread & poultry sausage)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 22,
    energyKcal: 250,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-bacon-toucinho-fumado",
    type: "ingredient",
    names: {
      pt: { name: "Bacon (toucinho fumado)", synonyms: ["toucinho", "bacon fumado"] },
      en: { name: "Bacon (smoked pork belly)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.5,
    energyKcal: 400,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["breakfast", "lunch", "dinner"],
  },

  // --- Fish (available carb = 0) -----------------------------------------
  {
    id: "pt-po-bacalhau-demolhado",
    type: "ingredient",
    names: {
      pt: { name: "Bacalhau salgado demolhado", synonyms: ["bacalhau demolhado"] },
      en: { name: "Salt cod, soaked", synonyms: ["desalted cod"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 130,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-sardinha",
    type: "ingredient",
    names: {
      pt: { name: "Sardinha", synonyms: ["sardinha assada"] },
      en: { name: "Sardine", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 205,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-carapau",
    type: "ingredient",
    names: {
      pt: { name: "Carapau", synonyms: ["chicharro"] },
      en: { name: "Horse mackerel", synonyms: ["scad"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 120,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-pescada",
    type: "ingredient",
    names: {
      pt: { name: "Pescada", synonyms: ["pescada cozida"] },
      en: { name: "Hake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 90,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-dourada",
    type: "ingredient",
    names: {
      pt: { name: "Dourada", synonyms: ["dourada grelhada"] },
      en: { name: "Gilthead sea bream", synonyms: ["sea bream"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 100,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-salmao",
    type: "ingredient",
    names: {
      pt: { name: "Salmão", synonyms: ["salmão grelhado"] },
      en: { name: "Salmon", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 200,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-atum-fresco",
    type: "ingredient",
    names: {
      pt: { name: "Atum fresco", synonyms: ["bife de atum"] },
      en: { name: "Fresh tuna", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 130,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-atum-lata-natural",
    type: "packaged",
    names: {
      pt: { name: "Atum em lata ao natural", synonyms: ["atum em água"] },
      en: { name: "Canned tuna in brine", synonyms: ["tuna in water"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 110,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-po-atum-lata-oleo",
    type: "packaged",
    names: {
      pt: { name: "Atum em lata em óleo", synonyms: ["atum em azeite"] },
      en: { name: "Canned tuna in oil", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 190,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-po-cavala",
    type: "ingredient",
    names: {
      pt: { name: "Cavala", synonyms: ["cavala grelhada"] },
      en: { name: "Mackerel", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 205,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-peixe-espada-preto",
    type: "ingredient",
    names: {
      pt: { name: "Peixe-espada preto", synonyms: ["espada", "peixe-espada"] },
      en: { name: "Black scabbardfish", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 110,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },

  // --- Seafood (small carb from glycogen) --------------------------------
  {
    id: "pt-po-camarao",
    type: "ingredient",
    names: {
      pt: { name: "Camarão", synonyms: ["camarão cozido", "gambas"] },
      en: { name: "Shrimp", synonyms: ["prawns"] },
    },
    countries: ["PT"],
    carbGrams: 0.5,
    energyKcal: 85,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-po-ameijoa",
    type: "ingredient",
    names: {
      pt: { name: "Amêijoa", synonyms: ["amêijoas à Bulhão Pato"] },
      en: { name: "Clams", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2.5,
    energyKcal: 75,
    confidence: "medium",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-po-mexilhao",
    type: "ingredient",
    names: {
      pt: { name: "Mexilhão", synonyms: ["mexilhões"] },
      en: { name: "Mussels", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.5,
    energyKcal: 85,
    confidence: "medium",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-po-lula",
    type: "ingredient",
    names: {
      pt: { name: "Lula", synonyms: ["lulas grelhadas"] },
      en: { name: "Squid", synonyms: ["calamari"] },
    },
    countries: ["PT"],
    carbGrams: 3,
    energyKcal: 92,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-polvo",
    type: "ingredient",
    names: {
      pt: { name: "Polvo", synonyms: ["polvo à lagareiro"] },
      en: { name: "Octopus", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2,
    energyKcal: 82,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-ostra",
    type: "ingredient",
    names: {
      pt: { name: "Ostra", synonyms: ["ostras"] },
      en: { name: "Oyster", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.5,
    energyKcal: 70,
    confidence: "medium",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },

  // --- Eggs (vegetarian) --------------------------------------------------
  {
    id: "pt-po-ovo-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Ovo cozido", synonyms: ["ovo de galinha cozido"] },
      en: { name: "Boiled egg", synonyms: ["hard-boiled egg"] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 155,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-po-ovo-estrelado",
    type: "ingredient",
    names: {
      pt: { name: "Ovo estrelado", synonyms: ["ovo frito"] },
      en: { name: "Fried egg", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 195,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "pt-po-ovo-mexido",
    type: "ingredient",
    names: {
      pt: { name: "Ovo mexido", synonyms: ["ovos mexidos"] },
      en: { name: "Scrambled eggs", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.5,
    energyKcal: 165,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "pt-po-clara-de-ovo",
    type: "ingredient",
    names: {
      pt: { name: "Clara de ovo", synonyms: ["claras"] },
      en: { name: "Egg white", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.7,
    energyKcal: 52,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-gema-de-ovo",
    type: "ingredient",
    names: {
      pt: { name: "Gema de ovo", synonyms: ["gemas"] },
      en: { name: "Egg yolk", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.6,
    energyKcal: 322,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast"],
  },

  // --- Cheese & dairy (vegetarian) ---------------------------------------
  {
    id: "pt-po-queijo-flamengo",
    type: "packaged",
    names: {
      pt: { name: "Queijo flamengo", synonyms: ["queijo em fatias"] },
      en: { name: "Flamengo cheese (edam-style)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 350,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-queijo-da-serra",
    type: "ingredient",
    names: {
      pt: { name: "Queijo da Serra", synonyms: ["Serra da Estrela"] },
      en: { name: "Serra da Estrela cheese", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.5,
    energyKcal: 370,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-queijo-fresco",
    type: "ingredient",
    names: {
      pt: { name: "Queijo fresco", synonyms: ["queijinho fresco"] },
      en: { name: "Fresh cheese", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3,
    energyKcal: 110,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-requeijao",
    type: "ingredient",
    names: {
      pt: { name: "Requeijão", synonyms: ["requeijão de ovelha"] },
      en: { name: "Requeijão (whey cheese)", synonyms: ["ricotta-style cheese"] },
    },
    countries: ["PT"],
    carbGrams: 3.5,
    energyKcal: 130,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-po-queijo-de-cabra",
    type: "ingredient",
    names: {
      pt: { name: "Queijo de cabra", synonyms: ["queijo de cabra curado"] },
      en: { name: "Goat cheese", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 360,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-queijo-de-ovelha-curado",
    type: "ingredient",
    names: {
      pt: { name: "Queijo de ovelha curado", synonyms: ["queijo de ovelha"] },
      en: { name: "Cured sheep cheese", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 380,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-queijo-ralado",
    type: "packaged",
    names: {
      pt: { name: "Queijo ralado", synonyms: ["queijo para gratinar"] },
      en: { name: "Grated cheese", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.5,
    energyKcal: 400,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-po-iogurte-grego-natural",
    type: "packaged",
    names: {
      pt: { name: "Iogurte grego natural", synonyms: ["iogurte grego"] },
      en: { name: "Plain Greek yoghurt", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4,
    energyKcal: 115,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-po-iogurte-magro",
    type: "packaged",
    names: {
      pt: { name: "Iogurte magro", synonyms: ["iogurte natural magro"] },
      en: { name: "Low-fat yoghurt", synonyms: ["skimmed yoghurt"] },
    },
    countries: ["PT"],
    carbGrams: 4.5,
    energyKcal: 45,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-po-iogurte-de-aromas",
    type: "packaged",
    names: {
      pt: { name: "Iogurte de aromas", synonyms: ["iogurte de sabores", "iogurte açucarado"] },
      en: { name: "Flavoured yoghurt", synonyms: ["sweetened yoghurt"] },
    },
    countries: ["PT"],
    carbGrams: 13,
    energyKcal: 90,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-po-leite-gordo",
    type: "packaged",
    names: {
      pt: { name: "Leite gordo", synonyms: ["leite inteiro"] },
      en: { name: "Whole milk", synonyms: ["full-fat milk"] },
    },
    countries: ["PT"],
    carbGrams: 4.7,
    energyKcal: 64,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-leite-magro",
    type: "packaged",
    names: {
      pt: { name: "Leite magro", synonyms: ["leite desnatado"] },
      en: { name: "Skimmed milk", synonyms: ["non-fat milk"] },
    },
    countries: ["PT"],
    carbGrams: 4.9,
    energyKcal: 35,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-leite-sem-lactose",
    type: "packaged",
    names: {
      pt: { name: "Leite sem lactose", synonyms: ["leite deslactosado"] },
      en: { name: "Lactose-free milk", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.8,
    energyKcal: 42,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-manteiga",
    type: "packaged",
    names: {
      pt: { name: "Manteiga", synonyms: ["manteiga com sal"] },
      en: { name: "Butter", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.6,
    energyKcal: 745,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast"],
  },
  {
    id: "pt-po-natas",
    type: "packaged",
    names: {
      pt: { name: "Natas", synonyms: ["natas para culinária", "creme de leite"] },
      en: { name: "Cream", synonyms: ["cooking cream"] },
    },
    countries: ["PT"],
    carbGrams: 3,
    energyKcal: 340,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner", "dessert"],
  },
  {
    id: "pt-po-kefir",
    type: "packaged",
    names: {
      pt: { name: "Kefir", synonyms: ["kefir de leite"] },
      en: { name: "Kefir", synonyms: ["milk kefir"] },
    },
    countries: ["PT"],
    carbGrams: 4,
    energyKcal: 55,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-po-queijo-creme",
    type: "packaged",
    names: {
      pt: { name: "Queijo creme", synonyms: ["queijo creme para barrar"] },
      en: { name: "Cream cheese", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4,
    energyKcal: 255,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
];
