// Portugal — produce (fruit, vegetables, pulses/legumes, nuts & seeds).
// SYNTHETIC development data; per-100 g approximations with honest
// confidence/provenance. id prefix: `pt-pr-`.

import type { FoodInput } from "../catalogTypes.js";

export const PT_PRODUCE: FoodInput[] = [
  // ---------------------------------------------------------------------------
  // FRUIT (raw, whole; carb = available carbohydrate per 100 g)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pr-laranja",
    type: "ingredient",
    names: {
      pt: { name: "Laranja", synonyms: ["laranja do Algarve"] },
      en: { name: "Orange", synonyms: ["sweet orange"] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 47,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-pr-pera-rocha",
    type: "ingredient",
    names: {
      pt: { name: "Pêra rocha", synonyms: ["pera"] },
      en: { name: "Rocha pear", synonyms: ["pear"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 57,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-uva",
    type: "ingredient",
    names: {
      pt: { name: "Uva", synonyms: ["uvas", "cacho de uvas"] },
      en: { name: "Grapes", synonyms: ["table grapes"] },
    },
    countries: ["PT"],
    carbGrams: 16.0,
    energyKcal: 69,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-melao",
    type: "ingredient",
    names: {
      pt: { name: "Melão", synonyms: ["melão branco"] },
      en: { name: "Melon", synonyms: ["honeydew melon"] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 34,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-melancia",
    type: "ingredient",
    names: {
      pt: { name: "Melancia", synonyms: [] },
      en: { name: "Watermelon", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 30,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-morango",
    type: "ingredient",
    names: {
      pt: { name: "Morango", synonyms: ["morangos"] },
      en: { name: "Strawberry", synonyms: ["strawberries"] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 32,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-pessego",
    type: "ingredient",
    names: {
      pt: { name: "Pêssego", synonyms: ["pêssegos"] },
      en: { name: "Peach", synonyms: ["peaches"] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 39,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-ameixa",
    type: "ingredient",
    names: {
      pt: { name: "Ameixa", synonyms: ["ameixas"] },
      en: { name: "Plum", synonyms: ["plums"] },
    },
    countries: ["PT"],
    carbGrams: 10.0,
    energyKcal: 46,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-cereja",
    type: "ingredient",
    names: {
      pt: { name: "Cereja", synonyms: ["cerejas", "cereja do Fundão"] },
      en: { name: "Cherry", synonyms: ["cherries"] },
    },
    countries: ["PT"],
    carbGrams: 13.0,
    energyKcal: 63,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-figo",
    type: "ingredient",
    names: {
      pt: { name: "Figo", synonyms: ["figos"] },
      en: { name: "Fig", synonyms: ["figs", "fresh fig"] },
    },
    countries: ["PT"],
    carbGrams: 16.0,
    energyKcal: 74,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-kiwi",
    type: "ingredient",
    names: {
      pt: { name: "Kiwi", synonyms: ["quivi"] },
      en: { name: "Kiwifruit", synonyms: ["kiwi"] },
    },
    countries: ["PT"],
    carbGrams: 11.0,
    energyKcal: 61,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-pr-ananas",
    type: "ingredient",
    names: {
      pt: { name: "Ananás", synonyms: ["ananás dos Açores"] },
      en: { name: "Pineapple", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 50,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-manga",
    type: "ingredient",
    names: {
      pt: { name: "Manga", synonyms: ["mangas"] },
      en: { name: "Mango", synonyms: ["mangoes"] },
    },
    countries: ["PT"],
    carbGrams: 15.0,
    energyKcal: 60,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-tangerina",
    type: "ingredient",
    names: {
      pt: { name: "Tangerina", synonyms: ["clementina", "mandarina"] },
      en: { name: "Tangerine", synonyms: ["clementine", "mandarin"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 53,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-diospiro",
    type: "ingredient",
    names: {
      pt: { name: "Dióspiro", synonyms: ["diospiro", "caqui"] },
      en: { name: "Persimmon", synonyms: ["kaki", "sharon fruit"] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 70,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-roma",
    type: "ingredient",
    names: {
      pt: { name: "Romã", synonyms: ["romãs"] },
      en: { name: "Pomegranate", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 17.0,
    energyKcal: 83,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-framboesa",
    type: "ingredient",
    names: {
      pt: { name: "Framboesa", synonyms: ["framboesas"] },
      en: { name: "Raspberry", synonyms: ["raspberries"] },
    },
    countries: ["PT"],
    carbGrams: 5.0,
    energyKcal: 52,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-mirtilo",
    type: "ingredient",
    names: {
      pt: { name: "Mirtilo", synonyms: ["mirtilos"] },
      en: { name: "Blueberry", synonyms: ["blueberries"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 57,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-pr-abacate",
    type: "ingredient",
    names: {
      pt: { name: "Abacate", synonyms: ["abacates"] },
      en: { name: "Avocado", synonyms: ["avocados"] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 160,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pr-limao",
    type: "ingredient",
    names: {
      pt: { name: "Limão", synonyms: ["limões"] },
      en: { name: "Lemon", synonyms: ["lemons"] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 29,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: [],
  },
  {
    id: "pt-pr-tamara-seca",
    type: "ingredient",
    names: {
      pt: { name: "Tâmara seca", synonyms: ["tâmaras"] },
      en: { name: "Dried date", synonyms: ["dates"] },
    },
    countries: ["PT"],
    carbGrams: 63.0,
    energyKcal: 282,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-pr-passa-de-uva",
    type: "ingredient",
    names: {
      pt: { name: "Passa de uva", synonyms: ["passas", "uva passa"] },
      en: { name: "Raisin", synonyms: ["raisins"] },
    },
    countries: ["PT"],
    carbGrams: 79.0,
    energyKcal: 299,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },

  // ---------------------------------------------------------------------------
  // VEGETABLES (raw unless noted; carb = available carbohydrate per 100 g)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pr-couve-galega",
    type: "ingredient",
    names: {
      pt: { name: "Couve galega", synonyms: ["couve portuguesa", "couve de folhas"] },
      en: { name: "Galega kale", synonyms: ["Portuguese kale", "tronchuda kale"] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 30,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-couve-lombarda",
    type: "ingredient",
    names: {
      pt: { name: "Couve lombarda", synonyms: ["couve frisada"] },
      en: { name: "Savoy cabbage", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 27,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-brocolos",
    type: "ingredient",
    names: {
      pt: { name: "Brócolos", synonyms: ["brócolo"] },
      en: { name: "Broccoli", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.0,
    energyKcal: 34,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-couve-flor",
    type: "ingredient",
    names: {
      pt: { name: "Couve-flor", synonyms: [] },
      en: { name: "Cauliflower", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 25,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-cenoura",
    type: "ingredient",
    names: {
      pt: { name: "Cenoura", synonyms: ["cenouras"] },
      en: { name: "Carrot", synonyms: ["carrots"] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 41,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-pr-tomate",
    type: "ingredient",
    names: {
      pt: { name: "Tomate", synonyms: ["tomates"] },
      en: { name: "Tomato", synonyms: ["tomatoes"] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 18,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-alface",
    type: "ingredient",
    names: {
      pt: { name: "Alface", synonyms: ["alfaces"] },
      en: { name: "Lettuce", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 15,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-cebola",
    type: "ingredient",
    names: {
      pt: { name: "Cebola", synonyms: ["cebolas"] },
      en: { name: "Onion", synonyms: ["onions"] },
    },
    countries: ["PT"],
    carbGrams: 7.0,
    energyKcal: 40,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-alho",
    type: "ingredient",
    names: {
      pt: { name: "Alho", synonyms: ["dentes de alho"] },
      en: { name: "Garlic", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 130,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-alho-frances",
    type: "ingredient",
    names: {
      pt: { name: "Alho-francês", synonyms: ["alho francês"] },
      en: { name: "Leek", synonyms: ["leeks"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 61,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-pimento",
    type: "ingredient",
    names: {
      pt: { name: "Pimento", synonyms: ["pimentos", "pimento vermelho"] },
      en: { name: "Bell pepper", synonyms: ["sweet pepper", "capsicum"] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 31,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-courgette",
    type: "ingredient",
    names: {
      pt: { name: "Courgette", synonyms: ["curgete", "abobrinha"] },
      en: { name: "Courgette", synonyms: ["zucchini"] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 17,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-beringela",
    type: "ingredient",
    names: {
      pt: { name: "Beringela", synonyms: ["beringelas"] },
      en: { name: "Aubergine", synonyms: ["eggplant"] },
    },
    countries: ["PT"],
    carbGrams: 4.0,
    energyKcal: 25,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-abobora",
    type: "ingredient",
    names: {
      pt: { name: "Abóbora", synonyms: ["abóbora menina"] },
      en: { name: "Pumpkin", synonyms: ["squash"] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 26,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-espinafres",
    type: "ingredient",
    names: {
      pt: { name: "Espinafres", synonyms: ["espinafre"] },
      en: { name: "Spinach", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.4,
    energyKcal: 23,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-grelos",
    type: "ingredient",
    names: {
      pt: { name: "Grelos", synonyms: ["grelos de nabo"] },
      en: { name: "Turnip greens", synonyms: ["broccoli rabe", "rapini"] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 22,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-feijao-verde",
    type: "ingredient",
    names: {
      pt: { name: "Feijão-verde", synonyms: ["feijão verde"] },
      en: { name: "Green beans", synonyms: ["string beans"] },
    },
    countries: ["PT"],
    carbGrams: 5.0,
    energyKcal: 31,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-ervilhas-frescas",
    type: "ingredient",
    names: {
      pt: { name: "Ervilhas frescas", synonyms: ["ervilha"] },
      en: { name: "Fresh peas", synonyms: ["green peas"] },
    },
    countries: ["PT"],
    carbGrams: 10.0,
    energyKcal: 81,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-favas-frescas",
    type: "ingredient",
    names: {
      pt: { name: "Favas frescas", synonyms: ["fava"] },
      en: { name: "Fresh broad beans", synonyms: ["fava beans"] },
    },
    countries: ["PT"],
    carbGrams: 11.0,
    energyKcal: 88,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-cogumelos",
    type: "ingredient",
    names: {
      pt: { name: "Cogumelos", synonyms: ["cogumelo branco"] },
      en: { name: "Mushrooms", synonyms: ["button mushrooms"] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 22,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },

  // ---------------------------------------------------------------------------
  // PULSES / LEGUMES (cooked unless noted; carb = available carbohydrate per 100 g)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pr-grao-de-bico-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Grão-de-bico cozido", synonyms: ["grão cozido"] },
      en: { name: "Cooked chickpeas", synonyms: ["boiled chickpeas", "garbanzo"] },
    },
    countries: ["PT"],
    carbGrams: 27.0,
    energyKcal: 164,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-feijao-branco-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Feijão branco cozido", synonyms: ["feijão manteiga branco"] },
      en: { name: "Cooked white beans", synonyms: ["cannellini beans"] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 139,
    confidence: "high",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-feijao-encarnado-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Feijão encarnado cozido", synonyms: ["feijão vermelho"] },
      en: { name: "Cooked kidney beans", synonyms: ["red beans"] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 127,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-feijao-manteiga-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Feijão manteiga cozido", synonyms: ["feijão-manteiga"] },
      en: { name: "Cooked butter beans", synonyms: ["lima beans"] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 115,
    confidence: "high",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-feijao-frade-cozido",
    type: "ingredient",
    names: {
      pt: { name: "Feijão frade cozido", synonyms: ["feijão-frade"] },
      en: { name: "Cooked black-eyed peas", synonyms: ["cowpeas"] },
    },
    countries: ["PT"],
    carbGrams: 21.0,
    energyKcal: 116,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-lentilhas-cozidas",
    type: "ingredient",
    names: {
      pt: { name: "Lentilhas cozidas", synonyms: ["lentilha"] },
      en: { name: "Cooked lentils", synonyms: ["boiled lentils"] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 116,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-ervilhas-cozidas",
    type: "ingredient",
    names: {
      pt: { name: "Ervilhas cozidas", synonyms: ["ervilha cozida"] },
      en: { name: "Cooked peas", synonyms: ["boiled green peas"] },
    },
    countries: ["PT"],
    carbGrams: 13.0,
    energyKcal: 84,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-favas-cozidas",
    type: "ingredient",
    names: {
      pt: { name: "Favas cozidas", synonyms: ["fava cozida"] },
      en: { name: "Cooked broad beans", synonyms: ["boiled fava beans"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 110,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pr-grao-de-bico-enlatado",
    type: "ingredient",
    names: {
      pt: { name: "Grão-de-bico enlatado", synonyms: ["grão de conserva"] },
      en: { name: "Canned chickpeas", synonyms: ["tinned chickpeas"] },
    },
    countries: ["PT"],
    carbGrams: 22.0,
    energyKcal: 139,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },

  // ---------------------------------------------------------------------------
  // NUTS & SEEDS (raw/roasted; carb = available carbohydrate per 100 g)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pr-amendoa",
    type: "ingredient",
    names: {
      pt: { name: "Amêndoa", synonyms: ["amêndoas"] },
      en: { name: "Almond", synonyms: ["almonds"] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 579,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-noz",
    type: "ingredient",
    names: {
      pt: { name: "Noz", synonyms: ["nozes"] },
      en: { name: "Walnut", synonyms: ["walnuts"] },
    },
    countries: ["PT"],
    carbGrams: 7.0,
    energyKcal: 654,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-avela",
    type: "ingredient",
    names: {
      pt: { name: "Avelã", synonyms: ["avelãs"] },
      en: { name: "Hazelnut", synonyms: ["hazelnuts"] },
    },
    countries: ["PT"],
    carbGrams: 7.0,
    energyKcal: 628,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-amendoim",
    type: "ingredient",
    names: {
      pt: { name: "Amendoim", synonyms: ["amendoins"] },
      en: { name: "Peanut", synonyms: ["peanuts", "groundnut"] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 567,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-castanha-assada",
    type: "ingredient",
    names: {
      pt: { name: "Castanha assada", synonyms: ["castanhas", "castanha cozida"] },
      en: { name: "Roasted chestnut", synonyms: ["chestnuts"] },
    },
    countries: ["PT"],
    carbGrams: 36.0,
    energyKcal: 196,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-pinhao",
    type: "ingredient",
    names: {
      pt: { name: "Pinhão", synonyms: ["pinhões"] },
      en: { name: "Pine nuts", synonyms: ["pine kernels"] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 673,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-sementes-de-girassol",
    type: "packaged",
    names: {
      pt: { name: "Sementes de girassol", synonyms: ["semente de girassol"] },
      en: { name: "Sunflower seeds", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 11.0,
    energyKcal: 584,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-sementes-de-abobora",
    type: "packaged",
    names: {
      pt: { name: "Sementes de abóbora", synonyms: ["semente de abóbora"] },
      en: { name: "Pumpkin seeds", synonyms: ["pepitas"] },
    },
    countries: ["PT"],
    carbGrams: 5.0,
    energyKcal: 559,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pr-sementes-de-chia",
    type: "packaged",
    names: {
      pt: { name: "Sementes de chia", synonyms: ["chia"] },
      en: { name: "Chia seeds", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 486,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pr-sementes-de-linhaca",
    type: "packaged",
    names: {
      pt: { name: "Sementes de linhaça", synonyms: ["linhaça"] },
      en: { name: "Flaxseed", synonyms: ["linseed"] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 534,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
];
