// Portugal — cooked dishes (traditional & regional mains, soups, petiscos, and
// common fast food eaten in Portugal). SYNTHETIC development data; per-100 g
// approximations with honest confidence/provenance. id prefix: `pt-ds-`.

import type { FoodInput } from "../catalogTypes.js";

export const PT_DISHES: FoodInput[] = [
  // ── Mains: rice-based ──────────────────────────────────────────────
  {
    id: "pt-ds-arroz-de-marisco",
    type: "recipe",
    names: {
      pt: { name: "Arroz de marisco", synonyms: [] },
      en: { name: "Portuguese seafood rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 130,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-arroz-de-pato",
    type: "recipe",
    names: {
      pt: { name: "Arroz de pato", synonyms: ["Arroz de pato à antiga"] },
      en: { name: "Duck rice", synonyms: ["Baked duck rice"] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 190,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-arroz-de-tamboril",
    type: "recipe",
    names: {
      pt: { name: "Arroz de tamboril", synonyms: [] },
      en: { name: "Monkfish rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 16.0,
    energyKcal: 120,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-arroz-de-polvo",
    type: "recipe",
    names: {
      pt: { name: "Arroz de polvo", synonyms: [] },
      en: { name: "Octopus rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 17.0,
    energyKcal: 125,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-arroz-de-cabidela",
    type: "recipe",
    names: {
      pt: { name: "Arroz de cabidela", synonyms: ["Cabidela de frango"] },
      en: { name: "Chicken blood rice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 19.0,
    energyKcal: 160,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  // ── Mains: bacalhau ────────────────────────────────────────────────
  {
    id: "pt-ds-bacalhau-com-natas",
    type: "recipe",
    names: {
      pt: { name: "Bacalhau com natas", synonyms: [] },
      en: { name: "Salt cod with cream", synonyms: ["Cod gratin with cream"] },
    },
    countries: ["PT"],
    carbGrams: 12.0,
    energyKcal: 180,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-bacalhau-a-gomes-de-sa",
    type: "recipe",
    names: {
      pt: { name: "Bacalhau à Gomes de Sá", synonyms: [] },
      en: { name: "Cod Gomes de Sá", synonyms: ["Cod with potato, egg and olives"] },
    },
    countries: ["PT"],
    carbGrams: 10.0,
    energyKcal: 160,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-bacalhau-a-lagareiro",
    type: "recipe",
    names: {
      pt: { name: "Bacalhau à lagareiro", synonyms: [] },
      en: { name: "Cod à lagareiro", synonyms: ["Roasted cod with smashed potatoes"] },
    },
    countries: ["PT"],
    carbGrams: 11.0,
    energyKcal: 185,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-bacalhau-com-broa",
    type: "recipe",
    names: {
      pt: { name: "Bacalhau com broa", synonyms: ["Bacalhau com crosta de broa"] },
      en: { name: "Cod with cornbread crust", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 13.0,
    energyKcal: 190,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-bacalhau-a-ze-do-pipo",
    type: "recipe",
    names: {
      pt: { name: "Bacalhau à Zé do Pipo", synonyms: [] },
      en: { name: "Cod à Zé do Pipo", synonyms: ["Cod with mashed potato and mayonnaise"] },
    },
    countries: ["PT"],
    carbGrams: 11.0,
    energyKcal: 170,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-pataniscas-de-bacalhau",
    type: "recipe",
    names: {
      pt: { name: "Pataniscas de bacalhau", synonyms: [] },
      en: { name: "Salt cod fritters", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 19.0,
    energyKcal: 220,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-ds-pasteis-de-bacalhau",
    type: "recipe",
    names: {
      pt: { name: "Pastéis de bacalhau", synonyms: ["Bolinhos de bacalhau"] },
      en: { name: "Salt cod cakes", synonyms: ["Cod croquettes"] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 210,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  // ── Mains: pork & beef ─────────────────────────────────────────────
  {
    id: "pt-ds-cozido-a-portuguesa",
    type: "recipe",
    names: {
      pt: { name: "Cozido à portuguesa", synonyms: [] },
      en: { name: "Portuguese boiled dinner", synonyms: ["Mixed boiled meats and vegetables"] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 160,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-feijoada-a-transmontana",
    type: "recipe",
    names: {
      pt: { name: "Feijoada à transmontana", synonyms: [] },
      en: { name: "Trás-os-Montes bean and pork stew", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 11.0,
    energyKcal: 180,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-rojoes-a-minhota",
    type: "recipe",
    names: {
      pt: { name: "Rojões à minhota", synonyms: [] },
      en: { name: "Minho-style fried pork", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.0,
    energyKcal: 250,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-carne-de-porco-a-alentejana",
    type: "recipe",
    names: {
      pt: { name: "Carne de porco à alentejana", synonyms: [] },
      en: { name: "Pork and clams Alentejo-style", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 180,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-febras-grelhadas",
    type: "recipe",
    names: {
      pt: { name: "Febras grelhadas", synonyms: [] },
      en: { name: "Grilled pork loin steaks", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.0,
    energyKcal: 170,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-bitoque",
    type: "recipe",
    names: {
      pt: { name: "Bitoque", synonyms: [] },
      en: { name: "Portuguese steak with fried egg", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 13.0,
    energyKcal: 190,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-jardineira",
    type: "recipe",
    names: {
      pt: { name: "Jardineira", synonyms: ["Carne guisada à jardineira"] },
      en: { name: "Portuguese meat and vegetable stew", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 110,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-dobrada-a-moda-do-porto",
    type: "recipe",
    names: {
      pt: { name: "Tripas à moda do Porto", synonyms: ["Dobrada à moda do Porto"] },
      en: { name: "Porto-style tripe with white beans", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 150,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-iscas-com-elas",
    type: "recipe",
    names: {
      pt: { name: "Iscas com elas", synonyms: [] },
      en: { name: "Lisbon-style liver with potatoes", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 160,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-moelas-guisadas",
    type: "recipe",
    names: {
      pt: { name: "Moelas guisadas", synonyms: [] },
      en: { name: "Stewed chicken gizzards", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.0,
    energyKcal: 130,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  {
    id: "pt-ds-pica-pau",
    type: "recipe",
    names: {
      pt: { name: "Pica-pau", synonyms: [] },
      en: { name: "Sautéed meat bites in sauce", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.0,
    energyKcal: 170,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  // ── Mains: poultry, roasts & game ──────────────────────────────────
  {
    id: "pt-ds-frango-assado",
    type: "recipe",
    names: {
      pt: { name: "Frango assado", synonyms: [] },
      en: { name: "Roast chicken", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.0,
    energyKcal: 200,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-frango-piri-piri",
    type: "recipe",
    names: {
      pt: { name: "Frango no churrasco com piri-piri", synonyms: ["Frango piri-piri"] },
      en: { name: "Grilled piri-piri chicken", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.5,
    energyKcal: 210,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-leitao-da-bairrada",
    type: "recipe",
    names: {
      pt: { name: "Leitão da Bairrada", synonyms: ["Leitão assado"] },
      en: { name: "Bairrada roast suckling pig", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.5,
    energyKcal: 280,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-cabrito-assado",
    type: "recipe",
    names: {
      pt: { name: "Cabrito assado", synonyms: [] },
      en: { name: "Roast kid goat", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1.0,
    energyKcal: 230,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-chanfana",
    type: "recipe",
    names: {
      pt: { name: "Chanfana", synonyms: [] },
      en: { name: "Goat stewed in red wine", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 180,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-coelho-a-cacador",
    type: "recipe",
    names: {
      pt: { name: "Coelho à caçador", synonyms: ["Coelho caçador"] },
      en: { name: "Hunter-style rabbit stew", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.0,
    energyKcal: 150,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-ensopado-de-borrego",
    type: "recipe",
    names: {
      pt: { name: "Ensopado de borrego", synonyms: [] },
      en: { name: "Lamb stew over bread", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 10.0,
    energyKcal: 150,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  // ── Mains: fish, seafood & bread-thickened ─────────────────────────
  {
    id: "pt-ds-sardinha-assada",
    type: "recipe",
    names: {
      pt: { name: "Sardinha assada", synonyms: ["Sardinhas assadas"] },
      en: { name: "Grilled sardines", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.0,
    energyKcal: 200,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-polvo-a-lagareiro",
    type: "recipe",
    names: {
      pt: { name: "Polvo à lagareiro", synonyms: [] },
      en: { name: "Octopus à lagareiro", synonyms: ["Roasted octopus with smashed potatoes"] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 150,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-acorda-de-marisco",
    type: "recipe",
    names: {
      pt: { name: "Açorda de marisco", synonyms: [] },
      en: { name: "Seafood bread stew", synonyms: ["Bread and shellfish porridge"] },
    },
    countries: ["PT"],
    carbGrams: 14.0,
    energyKcal: 130,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-migas",
    type: "recipe",
    names: {
      pt: { name: "Migas", synonyms: ["Migas alentejanas"] },
      en: { name: "Alentejo bread migas", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 200,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  // ── Mains: legumes & egg dishes ────────────────────────────────────
  {
    id: "pt-ds-favas-a-portuguesa",
    type: "recipe",
    names: {
      pt: { name: "Favas à portuguesa", synonyms: ["Favas com chouriço"] },
      en: { name: "Broad beans with cured pork", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 10.0,
    energyKcal: 140,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-ervilhas-guisadas-com-ovos",
    type: "recipe",
    names: {
      pt: { name: "Ervilhas guisadas com ovos", synonyms: ["Ervilhas com ovos escalfados"] },
      en: { name: "Stewed peas with poached eggs", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 120,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  // ── Soups ──────────────────────────────────────────────────────────
  {
    id: "pt-ds-sopa-de-legumes",
    type: "recipe",
    names: {
      pt: { name: "Sopa de legumes", synonyms: ["Sopa de hortaliça"] },
      en: { name: "Vegetable soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 45,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian", "vegan"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-sopa-de-feijao",
    type: "recipe",
    names: {
      pt: { name: "Sopa de feijão", synonyms: [] },
      en: { name: "Bean soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 8.0,
    energyKcal: 70,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-sopa-da-pedra",
    type: "recipe",
    names: {
      pt: { name: "Sopa da pedra", synonyms: [] },
      en: { name: "Stone soup", synonyms: ["Almeirim bean and meat soup"] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 90,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-sopa-de-peixe",
    type: "recipe",
    names: {
      pt: { name: "Sopa de peixe", synonyms: [] },
      en: { name: "Fish soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 5.0,
    energyKcal: 60,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-canja-de-galinha",
    type: "recipe",
    names: {
      pt: { name: "Canja de galinha", synonyms: [] },
      en: { name: "Chicken and rice soup", synonyms: ["Portuguese chicken canja"] },
    },
    countries: ["PT"],
    carbGrams: 7.0,
    energyKcal: 55,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-creme-de-legumes",
    type: "recipe",
    names: {
      pt: { name: "Creme de legumes", synonyms: ["Sopa creme de legumes"] },
      en: { name: "Creamed vegetable soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 55,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-gaspacho-alentejano",
    type: "recipe",
    names: {
      pt: { name: "Gaspacho alentejano", synonyms: [] },
      en: { name: "Alentejo cold tomato and bread soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 7.0,
    energyKcal: 60,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian", "vegan"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-sopa-de-grao",
    type: "recipe",
    names: {
      pt: { name: "Sopa de grão", synonyms: ["Sopa de grão-de-bico"] },
      en: { name: "Chickpea soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 9.0,
    energyKcal: 80,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-sopa-juliana",
    type: "recipe",
    names: {
      pt: { name: "Sopa juliana", synonyms: [] },
      en: { name: "Julienne vegetable soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 5.0,
    energyKcal: 40,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian", "vegan"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-ds-sopa-de-agriao",
    type: "recipe",
    names: {
      pt: { name: "Sopa de agrião", synonyms: ["Caldo de agriões"] },
      en: { name: "Watercress soup", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 5.0,
    energyKcal: 45,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian", "vegan"],
    mealContextTags: ["lunch", "dinner"],
  },
  // ── Petiscos & snacks ──────────────────────────────────────────────
  {
    id: "pt-ds-rissol-de-camarao",
    type: "recipe",
    names: {
      pt: { name: "Rissol de camarão", synonyms: ["Rissóis de camarão"] },
      en: { name: "Shrimp rissole", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 22.0,
    energyKcal: 250,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-ds-croquete-de-carne",
    type: "recipe",
    names: {
      pt: { name: "Croquete de carne", synonyms: ["Croquetes de carne"] },
      en: { name: "Meat croquette", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 240,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-ds-pastel-de-massa-tenra",
    type: "recipe",
    names: {
      pt: { name: "Pastel de massa tenra", synonyms: [] },
      en: { name: "Soft-pastry meat turnover", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 24.0,
    energyKcal: 260,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-ds-empada-de-galinha",
    type: "recipe",
    names: {
      pt: { name: "Empada de galinha", synonyms: [] },
      en: { name: "Chicken pie", synonyms: ["Small chicken pastry"] },
    },
    countries: ["PT"],
    carbGrams: 26.0,
    energyKcal: 280,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-ds-peixinhos-da-horta",
    type: "recipe",
    names: {
      pt: { name: "Peixinhos da horta", synonyms: [] },
      en: { name: "Battered green beans", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 18.0,
    energyKcal: 180,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-ds-caracois",
    type: "recipe",
    names: {
      pt: { name: "Caracóis", synonyms: ["Caracóis à portuguesa"] },
      en: { name: "Stewed snails", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2.0,
    energyKcal: 90,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-ds-salada-de-polvo",
    type: "recipe",
    names: {
      pt: { name: "Salada de polvo", synonyms: [] },
      en: { name: "Octopus salad", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.0,
    energyKcal: 120,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["snack", "lunch"],
  },
  {
    id: "pt-ds-ovos-verdes",
    type: "recipe",
    names: {
      pt: { name: "Ovos verdes", synonyms: [] },
      en: { name: "Stuffed fried eggs", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 6.0,
    energyKcal: 180,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack"],
  },
  // ── Common eat-out / takeaway ──────────────────────────────────────
  {
    id: "pt-ds-hamburguer",
    type: "restaurant",
    names: {
      pt: { name: "Hambúrguer", synonyms: ["Hambúrguer no pão"] },
      en: { name: "Hamburger", synonyms: ["Beef burger"] },
    },
    countries: ["PT"],
    carbGrams: 22.0,
    energyKcal: 250,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-ds-cachorro-quente",
    type: "restaurant",
    names: {
      pt: { name: "Cachorro quente", synonyms: ["Cachorrinho"] },
      en: { name: "Hot dog", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 24.0,
    energyKcal: 260,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  {
    id: "pt-ds-pizza-fatia",
    type: "restaurant",
    names: {
      pt: { name: "Pizza (fatia)", synonyms: ["Fatia de pizza"] },
      en: { name: "Pizza slice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 28.0,
    energyKcal: 260,
    confidence: "medium",
    method: "calculated",
    cuisineTags: ["portuguese", "mediterranean"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "pt-ds-kebab-durum",
    type: "restaurant",
    names: {
      pt: { name: "Kebab / dürüm", synonyms: ["Dürüm", "Kebab de frango"] },
      en: { name: "Kebab wrap (dürüm)", synonyms: ["Doner kebab wrap"] },
    },
    countries: ["PT"],
    carbGrams: 20.0,
    energyKcal: 220,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    mealContextTags: ["lunch", "dinner", "snack"],
  },
];
