// Portugal — pantry & drinks (beverages, condiments/molhos, mercearia, packaged
// snacks). SYNTHETIC development data; per-100 g (or per-100 ml, expressed on a
// 100 g basis) approximations with honest confidence/provenance. id prefix:
// `pt-pn-`.

import type { FoodInput } from "../catalogTypes.js";

export const PT_PANTRY: FoodInput[] = [
  // ---------------------------------------------------------------------------
  // BEVERAGES (carb per 100 ml, expressed on the 100 g basis field)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pn-agua",
    type: "ingredient",
    names: {
      pt: { name: "Água", synonyms: ["água mineral", "água engarrafada"] },
      en: { name: "Water", synonyms: ["still water", "bottled water"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 0,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "pt-pn-cafe-bica",
    type: "ingredient",
    names: {
      pt: { name: "Café (bica/espresso)", synonyms: ["bica", "cafezinho"] },
      en: { name: "Espresso coffee", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 2,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-galao",
    type: "ingredient",
    names: {
      pt: { name: "Galão", synonyms: ["café com leite (galão)"] },
      en: { name: "Galão (tall milky coffee)", synonyms: ["milky coffee"] },
    },
    countries: ["PT"],
    carbGrams: 4.6,
    energyKcal: 42,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-meia-de-leite",
    type: "ingredient",
    names: {
      pt: { name: "Meia de leite", synonyms: ["café com leite"] },
      en: { name: "Meia de leite (half coffee half milk)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 4.7,
    energyKcal: 45,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-cha-preto",
    type: "ingredient",
    names: {
      pt: { name: "Chá preto (sem açúcar)", synonyms: ["chá"] },
      en: { name: "Black tea (unsweetened)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.2,
    energyKcal: 1,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-cha-verde",
    type: "ingredient",
    names: {
      pt: { name: "Chá verde (sem açúcar)", synonyms: [] },
      en: { name: "Green tea (unsweetened)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 1,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-sumo-maca",
    type: "packaged",
    names: {
      pt: { name: "Sumo de maçã", synonyms: ["néctar de maçã"] },
      en: { name: "Apple juice", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 11.5,
    energyKcal: 46,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-sumo-multifrutos",
    type: "packaged",
    names: {
      pt: { name: "Sumo multifrutos", synonyms: ["sumo de frutos", "néctar multifrutos"] },
      en: { name: "Multifruit juice", synonyms: ["mixed fruit juice"] },
    },
    countries: ["PT"],
    carbGrams: 11,
    energyKcal: 48,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-nectar-pessego",
    type: "packaged",
    names: {
      pt: { name: "Néctar de pêssego", synonyms: ["sumo de pêssego"] },
      en: { name: "Peach nectar", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 12.5,
    energyKcal: 54,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-refrigerante-cola",
    type: "packaged",
    names: {
      pt: { name: "Refrigerante de cola", synonyms: ["cola", "Coca-Cola"] },
      en: { name: "Cola soft drink", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 10.6,
    energyKcal: 42,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "snack"],
  },
  {
    id: "pt-pn-refrigerante-laranja",
    type: "packaged",
    names: {
      pt: { name: "Refrigerante de laranja", synonyms: ["laranjada", "Fanta laranja"] },
      en: { name: "Orange soft drink", synonyms: ["orange soda"] },
    },
    countries: ["PT"],
    carbGrams: 11.5,
    energyKcal: 47,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "snack"],
  },
  {
    id: "pt-pn-ice-tea",
    type: "packaged",
    names: {
      pt: { name: "Ice tea (chá gelado)", synonyms: ["chá gelado", "iced tea"] },
      en: { name: "Iced tea", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 6.5,
    energyKcal: 26,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pn-agua-tonica",
    type: "packaged",
    names: {
      pt: { name: "Água tónica", synonyms: ["tónica"] },
      en: { name: "Tonic water", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 8.8,
    energyKcal: 34,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "dinner"],
  },
  {
    id: "pt-pn-cerveja",
    type: "packaged",
    names: {
      pt: { name: "Cerveja (loira)", synonyms: ["cerveja lager", "imperial", "fino"] },
      en: { name: "Beer (lager)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 3.5,
    energyKcal: 43,
    confidence: "medium",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-cerveja-preta",
    type: "packaged",
    names: {
      pt: { name: "Cerveja preta", synonyms: ["cerveja escura"] },
      en: { name: "Dark beer (stout)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 5,
    energyKcal: 50,
    confidence: "medium",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-vinho-tinto",
    type: "ingredient",
    names: {
      pt: { name: "Vinho tinto", synonyms: [] },
      en: { name: "Red wine", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.6,
    energyKcal: 85,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-vinho-branco",
    type: "ingredient",
    names: {
      pt: { name: "Vinho branco", synonyms: [] },
      en: { name: "White wine", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 0.8,
    energyKcal: 82,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-vinho-verde",
    type: "ingredient",
    names: {
      pt: { name: "Vinho verde", synonyms: [] },
      en: { name: "Vinho verde (young Portuguese wine)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2.5,
    energyKcal: 75,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-vinho-porto",
    type: "ingredient",
    names: {
      pt: { name: "Vinho do Porto", synonyms: ["Porto", "vinho generoso"] },
      en: { name: "Port wine", synonyms: ["Porto"] },
    },
    countries: ["PT"],
    carbGrams: 13,
    energyKcal: 160,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["dinner", "dessert"],
  },
  {
    id: "pt-pn-aguardente",
    type: "ingredient",
    names: {
      pt: { name: "Aguardente", synonyms: ["bagaço", "aguardente vínica"] },
      en: { name: "Aguardente (grape spirit/brandy)", synonyms: ["spirit"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 231,
    confidence: "high",
    method: "analytical",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["dinner"],
  },
  {
    id: "pt-pn-batido-chocolate",
    type: "packaged",
    names: {
      pt: { name: "Batido de chocolate", synonyms: ["leite achocolatado", "batido"] },
      en: { name: "Chocolate milk drink", synonyms: ["chocolate milkshake"] },
    },
    countries: ["PT"],
    carbGrams: 11,
    energyKcal: 80,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-bebida-aveia",
    type: "packaged",
    names: {
      pt: { name: "Bebida de aveia", synonyms: ["leite de aveia"] },
      en: { name: "Oat drink", synonyms: ["oat milk"] },
    },
    countries: ["PT"],
    carbGrams: 6.5,
    energyKcal: 45,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-bebida-soja",
    type: "packaged",
    names: {
      pt: { name: "Bebida de soja", synonyms: ["leite de soja"] },
      en: { name: "Soy drink", synonyms: ["soy milk"] },
    },
    countries: ["PT"],
    carbGrams: 2.8,
    energyKcal: 39,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-limonada",
    type: "packaged",
    names: {
      pt: { name: "Limonada", synonyms: ["sumo de limão açucarado"] },
      en: { name: "Lemonade", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 9,
    energyKcal: 38,
    confidence: "medium",
    method: "estimated",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pn-sumol",
    type: "packaged",
    names: {
      pt: { name: "Sumol (refrigerante de fruta)", synonyms: ["Sumol laranja", "Sumol ananás"] },
      en: { name: "Sumol (Portuguese fruit soda)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 11,
    energyKcal: 46,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },

  // ---------------------------------------------------------------------------
  // CONDIMENTS & SAUCES (per 100 g)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pn-piri-piri-molho",
    type: "packaged",
    names: {
      pt: { name: "Molho de piri-piri", synonyms: ["piri-piri", "molho picante"] },
      en: { name: "Piri-piri hot sauce", synonyms: ["chilli sauce"] },
    },
    countries: ["PT"],
    carbGrams: 4,
    energyKcal: 30,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-mostarda",
    type: "packaged",
    names: {
      pt: { name: "Mostarda", synonyms: [] },
      en: { name: "Mustard", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 6,
    energyKcal: 100,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-ketchup",
    type: "packaged",
    names: {
      pt: { name: "Ketchup", synonyms: ["molho de tomate ketchup"] },
      en: { name: "Ketchup", synonyms: ["tomato ketchup"] },
    },
    countries: ["PT"],
    carbGrams: 25,
    energyKcal: 110,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-maionese",
    type: "packaged",
    names: {
      pt: { name: "Maionese", synonyms: [] },
      en: { name: "Mayonnaise", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 2,
    energyKcal: 680,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-polpa-tomate",
    type: "packaged",
    names: {
      pt: { name: "Molho de tomate (polpa)", synonyms: ["polpa de tomate", "tomate concentrado"] },
      en: { name: "Tomato sauce / passata", synonyms: ["tomato purée"] },
    },
    countries: ["PT"],
    carbGrams: 7,
    energyKcal: 38,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-molho-ingles",
    type: "packaged",
    names: {
      pt: { name: "Molho inglês", synonyms: ["Worcestershire"] },
      en: { name: "Worcestershire sauce", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 19,
    energyKcal: 78,
    confidence: "medium",
    method: "declared",
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-vinagre",
    type: "ingredient",
    names: {
      pt: { name: "Vinagre", synonyms: ["vinagre de vinho"] },
      en: { name: "Vinegar", synonyms: ["wine vinegar"] },
    },
    countries: ["PT"],
    carbGrams: 0.4,
    energyKcal: 19,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-mel",
    type: "ingredient",
    names: {
      pt: { name: "Mel", synonyms: ["mel de abelha"] },
      en: { name: "Honey", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 82,
    energyKcal: 304,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-compota-morango",
    type: "packaged",
    names: {
      pt: { name: "Doce/compota de morango", synonyms: ["compota de morango", "doce de morango"] },
      en: { name: "Strawberry jam", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 60,
    energyKcal: 250,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-marmelada",
    type: "packaged",
    names: {
      pt: { name: "Marmelada", synonyms: ["doce de marmelo"] },
      en: { name: "Marmelada (quince paste)", synonyms: ["quince cheese"] },
    },
    countries: ["PT"],
    carbGrams: 65,
    energyKcal: 260,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-pn-geleia-fruta",
    type: "packaged",
    names: {
      pt: { name: "Geleia de fruta", synonyms: ["geleia"] },
      en: { name: "Fruit jelly", synonyms: ["fruit preserve"] },
    },
    countries: ["PT"],
    carbGrams: 65,
    energyKcal: 258,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-molho-soja",
    type: "packaged",
    names: {
      pt: { name: "Molho de soja", synonyms: ["soja"] },
      en: { name: "Soy sauce", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 6,
    energyKcal: 60,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-molho-barbecue",
    type: "packaged",
    names: {
      pt: { name: "Molho barbecue", synonyms: ["molho BBQ", "churrasco"] },
      en: { name: "Barbecue sauce", synonyms: ["BBQ sauce"] },
    },
    countries: ["PT"],
    carbGrams: 40,
    energyKcal: 170,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-molho-alho",
    type: "packaged",
    names: {
      pt: { name: "Molho de alho", synonyms: ["molho de alho cremoso"] },
      en: { name: "Garlic sauce", synonyms: ["garlic mayo", "aioli"] },
    },
    countries: ["PT"],
    carbGrams: 5,
    energyKcal: 320,
    confidence: "medium",
    method: "estimated",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },

  // ---------------------------------------------------------------------------
  // MERCEARIA / SNACKS (per 100 g)
  // ---------------------------------------------------------------------------
  {
    id: "pt-pn-acucar-branco",
    type: "ingredient",
    names: {
      pt: { name: "Açúcar branco", synonyms: ["açúcar", "sacarose"] },
      en: { name: "White sugar", synonyms: ["granulated sugar"] },
    },
    countries: ["PT"],
    carbGrams: 100,
    energyKcal: 400,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-pn-acucar-mascavado",
    type: "ingredient",
    names: {
      pt: { name: "Açúcar mascavado", synonyms: ["açúcar amarelo", "açúcar castanho"] },
      en: { name: "Brown sugar", synonyms: ["muscovado sugar"] },
    },
    countries: ["PT"],
    carbGrams: 98,
    energyKcal: 380,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack", "dessert"],
  },
  {
    id: "pt-pn-sal",
    type: "ingredient",
    names: {
      pt: { name: "Sal", synonyms: ["sal fino", "flor de sal", "sal marinho"] },
      en: { name: "Salt", synonyms: ["table salt", "sea salt"] },
    },
    countries: ["PT"],
    carbGrams: 0,
    energyKcal: 0,
    confidence: "high",
    method: "analytical",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["lunch", "dinner"],
  },
  {
    id: "pt-pn-manteiga-amendoim",
    type: "packaged",
    names: {
      pt: { name: "Manteiga de amendoim", synonyms: ["pasta de amendoim"] },
      en: { name: "Peanut butter", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 14,
    energyKcal: 600,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-chocolate-po",
    type: "packaged",
    names: {
      pt: { name: "Chocolate em pó (achocolatado)", synonyms: ["achocolatado", "chocolate solúvel"] },
      en: { name: "Drinking chocolate powder", synonyms: ["cocoa drink powder"] },
    },
    countries: ["PT"],
    carbGrams: 78,
    energyKcal: 380,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-leite-condensado",
    type: "packaged",
    names: {
      pt: { name: "Leite condensado", synonyms: ["leite condensado açucarado"] },
      en: { name: "Condensed milk", synonyms: ["sweetened condensed milk"] },
    },
    countries: ["PT"],
    carbGrams: 55,
    energyKcal: 320,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-pn-cacau-po",
    type: "packaged",
    names: {
      pt: { name: "Cacau em pó (sem açúcar)", synonyms: ["cacau magro"] },
      en: { name: "Cocoa powder (unsweetened)", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 14,
    energyKcal: 350,
    confidence: "medium",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-pn-granola",
    type: "packaged",
    names: {
      pt: { name: "Granola", synonyms: ["muesli crocante"] },
      en: { name: "Granola", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 60,
    energyKcal: 450,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-barra-cereais",
    type: "packaged",
    names: {
      pt: { name: "Barra de cereais", synonyms: ["barrinha de cereais"] },
      en: { name: "Cereal bar", synonyms: ["granola bar"] },
    },
    countries: ["PT"],
    carbGrams: 65,
    energyKcal: 400,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-pn-tremocos",
    type: "packaged",
    names: {
      pt: { name: "Tremoços", synonyms: ["tremoço em salmoura"] },
      en: { name: "Lupini beans (brined)", synonyms: ["lupin beans"] },
    },
    countries: ["PT"],
    carbGrams: 4,
    energyKcal: 116,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pn-azeitonas",
    type: "packaged",
    names: {
      pt: { name: "Azeitonas", synonyms: ["azeitona", "azeitonas de conserva"] },
      en: { name: "Olives", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 1,
    energyKcal: 145,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "lunch", "dinner"],
  },
  {
    id: "pt-pn-batatas-fritas-pacote",
    type: "packaged",
    names: {
      pt: { name: "Batatas fritas de pacote", synonyms: ["batata frita", "chips"] },
      en: { name: "Potato crisps", synonyms: ["potato chips"] },
    },
    countries: ["PT"],
    carbGrams: 50,
    energyKcal: 535,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pn-pipocas",
    type: "packaged",
    names: {
      pt: { name: "Pipocas", synonyms: ["pipoca"] },
      en: { name: "Popcorn", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 58,
    energyKcal: 500,
    confidence: "medium",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pn-frutos-secos-salgados",
    type: "packaged",
    names: {
      pt: { name: "Frutos secos torrados e salgados", synonyms: ["mistura de frutos secos", "amendoins salgados"] },
      en: { name: "Roasted salted nuts", synonyms: ["mixed nuts"] },
    },
    countries: ["PT"],
    carbGrams: 13,
    energyKcal: 610,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack"],
  },
  {
    id: "pt-pn-cereais-chocolate",
    type: "packaged",
    names: {
      pt: { name: "Cereais de chocolate", synonyms: ["cereais de pequeno-almoço de chocolate"] },
      en: { name: "Chocolate breakfast cereal", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 77,
    energyKcal: 385,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-bolachas-arroz",
    type: "packaged",
    names: {
      pt: { name: "Bolachas de arroz", synonyms: ["tortitas de arroz", "galetes de arroz"] },
      en: { name: "Rice cakes", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 81,
    energyKcal: 387,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-pn-tostas",
    type: "packaged",
    names: {
      pt: { name: "Tostas / pão torrado", synonyms: ["tosta", "pão torrado", "regueifa torrada"] },
      en: { name: "Melba toast / rusks", synonyms: ["toasted bread"] },
    },
    countries: ["PT"],
    carbGrams: 72,
    energyKcal: 400,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-pn-flocos-milho",
    type: "packaged",
    names: {
      pt: { name: "Flocos de milho", synonyms: ["corn flakes", "cereais de milho"] },
      en: { name: "Corn flakes", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 84,
    energyKcal: 378,
    confidence: "high",
    method: "declared",
    dietaryPatternTags: ["vegan", "vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
];
