// Portugal — sweets & pastry (pastelaria, doçaria conventual, bolos,
// sobremesas). SYNTHETIC development data; per-100 g approximations with honest
// confidence/provenance. id prefix: `pt-sw-`.

import type { FoodInput } from "../catalogTypes.js";

export const PT_SWEETS: FoodInput[] = [
  // --- Pastelaria (bakery / café pastries) -----------------------------------
  {
    id: "pt-sw-bolo-de-arroz",
    type: "packaged",
    names: {
      pt: { name: "Bolo de arroz", synonyms: [] },
      en: { name: "Portuguese rice muffin", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 52.0,
    energyKcal: 350,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-sw-queque",
    type: "packaged",
    names: {
      pt: { name: "Queque", synonyms: ["Queque simples"] },
      en: { name: "Portuguese cupcake", synonyms: ["Plain muffin"] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 380,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-sw-croissant-brioche",
    type: "packaged",
    names: {
      pt: { name: "Croissant", synonyms: ["Croissant brioche"] },
      en: { name: "Portuguese brioche croissant", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 405,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-sw-pao-de-deus",
    type: "packaged",
    names: {
      pt: { name: "Pão de deus", synonyms: [] },
      en: { name: "Coconut-topped sweet bun", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 320,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["breakfast", "snack"],
  },
  {
    id: "pt-sw-pao-de-lo",
    type: "packaged",
    names: {
      pt: { name: "Pão de ló", synonyms: ["Pão de ló de Ovar"] },
      en: { name: "Portuguese sponge cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 52.0,
    energyKcal: 330,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-bola-de-berlim",
    type: "packaged",
    names: {
      pt: { name: "Bola de Berlim", synonyms: [] },
      en: { name: "Portuguese Berliner doughnut", synonyms: ["Cream-filled doughnut"] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 355,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-sw-jesuita",
    type: "packaged",
    names: {
      pt: { name: "Jesuíta", synonyms: [] },
      en: { name: "Jesuita puff pastry", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 440,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-tarte-de-amendoa",
    type: "packaged",
    names: {
      pt: { name: "Tarte de amêndoa", synonyms: [] },
      en: { name: "Almond tart", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 42.0,
    energyKcal: 450,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-travesseiro-de-sintra",
    type: "packaged",
    names: {
      pt: { name: "Travesseiro de Sintra", synonyms: [] },
      en: { name: "Sintra almond puff pastry", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 40.0,
    energyKcal: 420,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-pastel-de-tentugal",
    type: "packaged",
    names: {
      pt: { name: "Pastel de Tentúgal", synonyms: [] },
      en: { name: "Tentugal egg cream pastry", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 400,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-queijada-de-sintra",
    type: "packaged",
    names: {
      pt: { name: "Queijada de Sintra", synonyms: [] },
      en: { name: "Sintra cheese tartlet", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 380,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-queijada-de-leite",
    type: "packaged",
    names: {
      pt: { name: "Queijada de leite", synonyms: [] },
      en: { name: "Milk tartlet", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 350,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-mil-folhas",
    type: "packaged",
    names: {
      pt: { name: "Mil-folhas", synonyms: [] },
      en: { name: "Millefeuille", synonyms: ["Napoleon pastry"] },
    },
    countries: ["PT"],
    carbGrams: 40.0,
    energyKcal: 380,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-eclair",
    type: "packaged",
    names: {
      pt: { name: "Éclair", synonyms: ["Eclair de chocolate"] },
      en: { name: "Eclair", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 35.0,
    energyKcal: 330,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-palmier",
    type: "packaged",
    names: {
      pt: { name: "Palmier", synonyms: ["Coração de folhado"] },
      en: { name: "Palmier", synonyms: ["Palm heart pastry"] },
    },
    countries: ["PT"],
    carbGrams: 55.0,
    energyKcal: 480,
    confidence: "medium",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-bolo-de-bolacha",
    type: "packaged",
    names: {
      pt: { name: "Bolo de bolacha", synonyms: [] },
      en: { name: "Biscuit and buttercream cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 400,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-tarte-de-maca",
    type: "packaged",
    names: {
      pt: { name: "Tarte de maçã", synonyms: [] },
      en: { name: "Apple tart", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 35.0,
    energyKcal: 260,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-folhado-de-creme",
    type: "packaged",
    names: {
      pt: { name: "Folhado de creme", synonyms: ["Folhado"] },
      en: { name: "Cream puff pastry", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 40.0,
    energyKcal: 370,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-duchesse",
    type: "packaged",
    names: {
      pt: { name: "Duchesse", synonyms: [] },
      en: { name: "Duchesse cream puff", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 34.0,
    energyKcal: 330,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },

  // --- Doçaria conventual (convent egg-and-sugar sweets) ---------------------
  {
    id: "pt-sw-ovos-moles-de-aveiro",
    type: "packaged",
    names: {
      pt: { name: "Ovos moles de Aveiro", synonyms: ["Ovos moles"] },
      en: { name: "Aveiro soft egg sweets", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 52.0,
    energyKcal: 330,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-toucinho-do-ceu",
    type: "packaged",
    names: {
      pt: { name: "Toucinho do céu", synonyms: [] },
      en: { name: "Almond and egg convent cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 420,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-papos-de-anjo",
    type: "packaged",
    names: {
      pt: { name: "Papos de anjo", synonyms: [] },
      en: { name: "Angel's cheeks egg sweets", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 300,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-barriga-de-freira",
    type: "packaged",
    names: {
      pt: { name: "Barriga de freira", synonyms: [] },
      en: { name: "Nun's belly egg dessert", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 330,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-encharcada",
    type: "packaged",
    names: {
      pt: { name: "Encharcada", synonyms: ["Encharcada do convento"] },
      en: { name: "Alentejo soaked egg sweet", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 300,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-fios-de-ovos",
    type: "packaged",
    names: {
      pt: { name: "Fios de ovos", synonyms: [] },
      en: { name: "Egg threads", synonyms: ["Angel hair egg sweet"] },
    },
    countries: ["PT"],
    carbGrams: 55.0,
    energyKcal: 320,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-lampreia-de-ovos",
    type: "packaged",
    names: {
      pt: { name: "Lampreia de ovos", synonyms: [] },
      en: { name: "Egg thread lamprey", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 55.0,
    energyKcal: 330,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-pastel-de-feijao",
    type: "packaged",
    names: {
      pt: { name: "Pastel de feijão", synonyms: [] },
      en: { name: "Bean and almond tartlet", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 380,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-dom-rodrigo",
    type: "packaged",
    names: {
      pt: { name: "Dom Rodrigo", synonyms: [] },
      en: { name: "Dom Rodrigo egg thread sweet", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 55.0,
    energyKcal: 400,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-broa-castelar",
    type: "packaged",
    names: {
      pt: { name: "Broa castelar", synonyms: ["Broas de batata-doce"] },
      en: { name: "Sweet potato and almond cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 350,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-bolo-de-mel-da-madeira",
    type: "packaged",
    names: {
      pt: { name: "Bolo de mel da Madeira", synonyms: ["Bolo de mel de cana"] },
      en: { name: "Madeira honey cake", synonyms: ["Madeira molasses cake"] },
    },
    countries: ["PT"],
    carbGrams: 55.0,
    energyKcal: 380,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-suspiros",
    type: "packaged",
    names: {
      pt: { name: "Suspiros", synonyms: ["Merengues"] },
      en: { name: "Meringue kisses", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 88.0,
    energyKcal: 400,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },

  // --- Bolos & sobremesas caseiras (homemade cakes & desserts) ---------------
  {
    id: "pt-sw-arroz-doce",
    type: "recipe",
    names: {
      pt: { name: "Arroz doce", synonyms: [] },
      en: { name: "Portuguese rice pudding", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 25.0,
    energyKcal: 150,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-leite-creme",
    type: "recipe",
    names: {
      pt: { name: "Leite-creme", synonyms: [] },
      en: { name: "Portuguese burnt custard", synonyms: ["Crème brûlée style custard"] },
    },
    countries: ["PT"],
    carbGrams: 22.0,
    energyKcal: 170,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-pudim-flan",
    type: "recipe",
    names: {
      pt: { name: "Pudim flan", synonyms: ["Pudim de ovos"] },
      en: { name: "Caramel flan pudding", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 28.0,
    energyKcal: 180,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-pudim-molotov",
    type: "recipe",
    names: {
      pt: { name: "Pudim molotov", synonyms: [] },
      en: { name: "Molotov egg-white pudding", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 30.0,
    energyKcal: 160,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-aletria",
    type: "recipe",
    names: {
      pt: { name: "Aletria", synonyms: [] },
      en: { name: "Sweet vermicelli pudding", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 28.0,
    energyKcal: 160,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-farofias",
    type: "recipe",
    names: {
      pt: { name: "Farófias", synonyms: ["Ilhas flutuantes"] },
      en: { name: "Floating islands", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 22.0,
    energyKcal: 130,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-rabanadas",
    type: "recipe",
    names: {
      pt: { name: "Rabanadas", synonyms: ["Fatias douradas"] },
      en: { name: "Portuguese French toast", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 35.0,
    energyKcal: 280,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-sonhos",
    type: "recipe",
    names: {
      pt: { name: "Sonhos", synonyms: [] },
      en: { name: "Fried dough puffs", synonyms: ["Portuguese dream fritters"] },
    },
    countries: ["PT"],
    carbGrams: 35.0,
    energyKcal: 320,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-filhos",
    type: "recipe",
    names: {
      pt: { name: "Filhós", synonyms: ["Filhoses"] },
      en: { name: "Fried dough fritters", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 38.0,
    energyKcal: 340,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-malassadas",
    type: "recipe",
    names: {
      pt: { name: "Malassadas", synonyms: ["Malasadas"] },
      en: { name: "Malassadas fried dough", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 35.0,
    energyKcal: 330,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-coscoroes",
    type: "recipe",
    names: {
      pt: { name: "Coscorões", synonyms: [] },
      en: { name: "Fried pastry ribbons", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 45.0,
    energyKcal: 420,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-mousse-de-chocolate",
    type: "recipe",
    names: {
      pt: { name: "Mousse de chocolate", synonyms: [] },
      en: { name: "Chocolate mousse", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 28.0,
    energyKcal: 270,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-salame-de-chocolate",
    type: "recipe",
    names: {
      pt: { name: "Salame de chocolate", synonyms: ["Salame de chocolate e bolacha"] },
      en: { name: "Chocolate salami", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 470,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-baba-de-camelo",
    type: "recipe",
    names: {
      pt: { name: "Baba de camelo", synonyms: [] },
      en: { name: "Camel's drool caramel mousse", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 40.0,
    energyKcal: 290,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-bolo-de-chocolate",
    type: "recipe",
    names: {
      pt: { name: "Bolo de chocolate", synonyms: [] },
      en: { name: "Chocolate cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 380,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-bolo-de-laranja",
    type: "recipe",
    names: {
      pt: { name: "Bolo de laranja", synonyms: [] },
      en: { name: "Orange cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 52.0,
    energyKcal: 370,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-bolo-rei",
    type: "recipe",
    names: {
      pt: { name: "Bolo-rei", synonyms: [] },
      en: { name: "King cake", synonyms: ["Portuguese Christmas fruit cake"] },
    },
    countries: ["PT"],
    carbGrams: 52.0,
    energyKcal: 350,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-bolo-rainha",
    type: "recipe",
    names: {
      pt: { name: "Bolo-rainha", synonyms: [] },
      en: { name: "Queen cake", synonyms: ["Nut king cake variant"] },
    },
    countries: ["PT"],
    carbGrams: 50.0,
    energyKcal: 360,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-torta-de-laranja",
    type: "recipe",
    names: {
      pt: { name: "Torta de laranja", synonyms: [] },
      en: { name: "Orange roll cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 48.0,
    energyKcal: 350,
    confidence: "medium",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-tigelada",
    type: "recipe",
    names: {
      pt: { name: "Tigelada", synonyms: ["Tigelada à moda da Beira"] },
      en: { name: "Baked egg custard", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 25.0,
    energyKcal: 190,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },
  {
    id: "pt-sw-sericaia",
    type: "recipe",
    names: {
      pt: { name: "Sericaia", synonyms: ["Sericá"] },
      en: { name: "Sericaia egg custard cake", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 35.0,
    energyKcal: 250,
    confidence: "low",
    method: "estimated",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert"],
  },

  // --- Doces embalados (industrial packaged) ---------------------------------
  {
    id: "pt-sw-bolachas-maria",
    type: "packaged",
    names: {
      pt: { name: "Bolachas Maria", synonyms: [] },
      en: { name: "Maria biscuits", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 75.0,
    energyKcal: 430,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-sw-bolacha-de-agua-e-sal",
    type: "packaged",
    names: {
      pt: { name: "Bolacha de água e sal", synonyms: [] },
      en: { name: "Water and salt crackers", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 70.0,
    energyKcal: 430,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack", "breakfast"],
  },
  {
    id: "pt-sw-gelado-de-baunilha",
    type: "packaged",
    names: {
      pt: { name: "Gelado de baunilha", synonyms: [] },
      en: { name: "Vanilla ice cream", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 24.0,
    energyKcal: 200,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-gelado-de-nata",
    type: "packaged",
    names: {
      pt: { name: "Gelado de nata", synonyms: [] },
      en: { name: "Cream ice cream", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 23.0,
    energyKcal: 210,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
  {
    id: "pt-sw-chocolate-de-leite-tablete",
    type: "packaged",
    names: {
      pt: { name: "Chocolate de leite (tablete)", synonyms: ["Tablete de chocolate de leite"] },
      en: { name: "Milk chocolate bar", synonyms: [] },
    },
    countries: ["PT"],
    carbGrams: 57.0,
    energyKcal: 535,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["snack", "dessert"],
  },
  {
    id: "pt-sw-gelatina",
    type: "packaged",
    names: {
      pt: { name: "Gelatina", synonyms: ["Gelatina de fruta"] },
      en: { name: "Fruit jelly", synonyms: ["Prepared gelatin dessert"] },
    },
    countries: ["PT"],
    carbGrams: 14.0,
    energyKcal: 60,
    confidence: "high",
    method: "declared",
    cuisineTags: ["portuguese"],
    dietaryPatternTags: ["vegetarian"],
    mealContextTags: ["dessert", "snack"],
  },
];
